version: "3.8"

services:
  mc:
    image: itzg/minecraft-bedrock-server
    tty: true
    stdin_open: true
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "os troxa"
      LEVEL_NAME: "os troxas"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "operator"
      ALLOW_CHEATS: true
      CORRECT_PLAYER_MOVEMENT: true
      ONLINE_MODE: false
      TICK_DISTANCE: 6
    volumes:
      - ./data:/data
